AWSTemplateFormatVersion: '2010-09-09'
Description: Doculet Lambda functions to support embeding of Doculet documents
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Export:
      Name: DoculetLambdaApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/oembed
Resources:
  PetStoreFunction:
    Properties:
      CodeUri: s3://doculet-lambda/33e705fcac0fad3b31c170be05ba00ea
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.doculet.lambda.StreamLambdaHandler::handleRequest
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
